# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.
main:
  - name: 집
    url: /#top
    weight: 10
  - name: 수출 컨설팅
    url: /#export-consultancy
    weight: 20
  - name: 문의하기
    url: /#contact
    weight: 30